### PR TITLE
massive improvments

### PR DESCRIPTION
**Pull request by Mr-PenguinMan**
https://github.com/MicrocontrollersDev/Alternatives/blob/main/SkyblockExtras.md

### CODE REVIEW

**Review by MicrocontrollersDev — APPROVED** [review]

**Review by TymanWasTaken — APPROVED** [review]

**Review by proudmuslim-dev — APPROVED** [review]

**Review by xcfrg — APPROVED** [review]

**Review by GamingGeek — APPROVED** [review]
LGTM!

**Review by fireflame606 — APPROVED** [review]

**Review by Kingili22 — APPROVED** [review]

**Review by IRONM00N — APPROVED** [review]

**Review by Ecorte — APPROVED** [review]

**Comment by Zordlan** [comment]
how the fuck do you do this approved these changes thing

**Review by Zordlan — APPROVED** [review]
OH THATS HOW

**Review by My-Name-Is-Jeff — APPROVED** [review]

**Comment by dogdudeisop** [comment]
this was stolen from someone else. He copied the exact code please don't give this man credit

**Comment by MicrocontrollersDev** [comment]
ready to merge

**Review by riohorealhk — APPROVED** [review]

**Review by apotato321 — APPROVED** [review]

**Comment by riohorealhk** [comment]
hello can u merge this @MatthewTGM

**Review by mozilal — APPROVED** [review]
LGTM! :+1:

**Comment by mozilal** [comment]
@MatthewTGM Hello Godforsaken Misogynist, we are requesting a merge

**Review by JosephE2 — COMMENTED** [review]
pog delete all of them this cunt is bad

**Review by JosephE2 — APPROVED** [review]

**Comment by Kingili22** [comment]
# please do this
you copied inv.wtf/fucksbe
just delete it, you edited it to add ur own mods and promote urself please just delete it :D

**Review by riohorealhk — APPROVED** [review]
e

**Review by MicrocontrollersDev — COMMENTED** [review]
wait i can review other reviews?

**Review by BlueDinoKing — APPROVED** [review]
👍

**Review by proudmuslim-dev — APPROVED** [review]

**Review by proudmuslim-dev — APPROVED** [review]

**Pull request closed without merging**
